###Importando o torch

In [34]:
import torch
print(torch.__version__)

2.1.0+cu121


##Tensores no Pytorch são criados com torch.tensor

##Tensors (ou tensores) são uma forma numérica de representar dados

###Tipos de tensores:

#SCALAR

######Representar uma certa interação

In [35]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

#VECTOR

In [36]:
# vector
vector = torch.tensor([7, 7])
vector.ndim

1

In [ ]:
#MATRIX

In [37]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

#TENSOR

In [38]:
#TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [39]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

###Tensor aleatório

In [40]:
random_tensor = torch.rand(2, 5, 4)
random_tensor, TENSOR.shape, TENSOR.ndim


(tensor([[[0.8694, 0.5677, 0.7411, 0.4294],
          [0.8854, 0.5739, 0.2666, 0.6274],
          [0.2696, 0.4414, 0.2969, 0.8317],
          [0.1053, 0.2695, 0.3588, 0.1994],
          [0.5472, 0.0062, 0.9516, 0.0753]],
 
         [[0.8860, 0.5832, 0.3376, 0.8090],
          [0.5779, 0.9040, 0.5547, 0.3423],
          [0.6343, 0.3644, 0.7104, 0.9464],
          [0.7890, 0.2814, 0.7886, 0.5895],
          [0.7539, 0.1952, 0.0050, 0.3068]]]),
 torch.Size([1, 3, 3]),
 3)

Tensores de Ones & Zeros

In [41]:
ones = torch.ones(size=(6, 7))
zeros = torch.zeros(size=(6, 7))
ones, zeros

(tensor([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]))

###Pegar informação de tensores

1. datatype (float, int, string) - tensor.dtype
2. shape - tensor.shape
3. device (gpu ou cpu)  - tensor.device

In [42]:
# criando tensor
some_tensor = torch.rand(5, 4)
some_tensor

tensor([[0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])

In [43]:
#Achar detalhes do tensor

print(some_tensor)
print(f"Dataype do tensor: {some_tensor.dtype}")
print(f"Shape do tensor: {some_tensor.shape}")
print(f"Device do tensor: {some_tensor.device}")

tensor([[0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])
Dataype do tensor: torch.float32
Shape do tensor: torch.Size([5, 4])
Device do tensor: cpu


###Manipulação de tensores (operações com tensor)

- Adicção
- Subtração
- Multicação (element-wise)
- Divisão
- Multiplicação de Matrix

In [44]:
#Soma com tensor

tensor = torch.tensor([1, 2, 3])
tensor + 50

tensor([51, 52, 53])

In [45]:
#Subtração com tensor

tensor = torch.tensor([1, 2, 3])
tensor - 40

tensor([-39, -38, -37])

In [46]:
#Multiplicando tensor

tensor = tensor * 30
tensor

tensor([30, 60, 90])

In [47]:
torch.mul(tensor, 10)

tensor([300, 600, 900])

####Multiplicação de matrix

- Existem 2 jeitos principais de multiplicação nos neural networks e deep learning

1. Element-wise multiplication
2. Matrix de multiplicação (dot product)

- +Info: https://www.mathsisfun.com/algebra/matrix-multiplying.html

- Existem duas regras principais enquanto performar a multiplicação de matrix

1. As dimensões de dentro (inner dimensions) tem que dar match com as mesmas:

- (3, 2) @ (3, 2) não funciona.
- (2, 3) @ (3, 2) funciona.
- (3, 2) @ (2, 3) funciona.

2. A matrix resultante tem o formato de dimensão de fora(outer dimension)

- (2, 3) @ (3, 2) -> (2, 2)
- (3, 2) @ (2, 3) -> (3, 3)

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3,2))

tensor([[1.0791, 0.8329],
        [1.1537, 0.7238]])

In [48]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Igual: {tensor * tensor}")

tensor([30, 60, 90]) * tensor([30, 60, 90])
Igual: tensor([ 900, 3600, 8100])


 - Diferente do element wise que só nos dá os números multiplicados, ele os soma no total também ⇩

In [50]:
#Matrix de multiplicação
torch.matmul(tensor, tensor)

tensor(12600)

In [51]:
tensor

tensor([30, 60, 90])

In [ ]:
# Matrix de multiplicação feita a mão (by hand)

1*1 + 2*2 + 3*3

14

In [52]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(12600)
CPU times: user 1.13 ms, sys: 0 ns, total: 1.13 ms
Wall time: 1.29 ms


###Pra consertar erros no shape, dá pra manipular o shape de um dos nossos tensores usando transposição (transpose).

A transpose troca as dimensões ou eixos do tensor dado.

In [53]:
#Reproducibility (Fazendo o random no random)

torch.rand(4, 4)

tensor([[0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115]])

In [29]:
#Colocando random seed(false)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [30]:
#Colocando random seed(true)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) #Colocando o manual_seed em um dos random_seed o true aparece
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Conseguir uma GPU

1 - Facil de conseguir é usando o Google collab free

In [54]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
